/** export シンボルの一覧を .cursor/rules/ に置き、モデルの glob/grep/read を減らす。全 run に注入されるので小さく保つ。 */
import { readdirSync, readFileSync, statSync } from "node:fs"
import { join, relative } from "node:path"

/** 約1k トークン。 */
export const MAP_CHAR_BUDGET = 4_000

const SYMBOL_RE = /^export\s+(?:async\s+)?(function|class|interface|type|const|enum)\s+([A-Za-z0-9_]+)/

export interface FileSymbols {
  file: string
  symbols: string[]
}

export function extractSymbols(source: string): string[] {
  const out: string[] = []
  for (const line of source.split("\n")) {
    const m = line.match(SYMBOL_RE)
    if (!m) continue
    const kind = m[1] as string
    const name = m[2] as string
    out.push(kind === "function" ? `${name}()` : kind === "class" ? `class ${name}` : name)
  }
  return out
}

function walkTsFiles(root: string, dir: string, acc: string[]): void {
  for (const name of readdirSync(dir)) {
    if (name === "node_modules" || name.startsWith(".")) continue
    const p = join(dir, name)
    const st = statSync(p)
    if (st.isDirectory()) walkTsFiles(root, p, acc)
    else if (name.endsWith(".ts") && !name.endsWith(".test.ts") && !name.endsWith(".d.ts")) acc.push(p)
  }
}

export function collectMap(cwd: string): FileSymbols[] {
  const files: string[] = []
  try {
    walkTsFiles(cwd, cwd, files)
  } catch {
    return []
  }
  const out: FileSymbols[] = []
  for (const f of files.sort()) {
    try {
      const symbols = extractSymbols(readFileSync(f, "utf8"))
      if (symbols.length > 0) out.push({ file: relative(cwd, f), symbols })
    } catch {
      // 読めないファイルは飛ばす
    }
  }
  return out
}

export function renderMap(map: FileSymbols[], budget = MAP_CHAR_BUDGET): string {
  const header = [
    "---",
    "alwaysApply: true",
    "---",
    "# Code map (generated by `villicus map` — do not edit; regenerate after structural changes)",
    "",
    "Exported symbols per file. Prefer this map over glob/grep exploration to locate code.",
    "",
  ].join("\n")
  const ranked = [...map].sort((a, b) => b.symbols.length - a.symbols.length)
  const lines: string[] = []
  let used = header.length
  let omitted = 0
  for (const fs of ranked) {
    const line = `- ${fs.file}: ${fs.symbols.join(", ")}`
    const clipped = line.length > 200 ? `${line.slice(0, 200)}…` : line
    if (used + clipped.length + 1 > budget) {
      omitted += 1
      continue
    }
    used += clipped.length + 1
    lines.push(clipped)
  }
  lines.sort()
  const footer = omitted > 0 ? `\n(…${omitted} more files omitted by budget — use grep for those)` : ""
  return `${header}${lines.join("\n")}${footer}\n`
}
